// Workspace.swift
import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: projectName,
    projects: ["."],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .targets(projectTargets.map { .target($0.name) }),
            testLanguage: "cs",
            testRegion: "CZ"
        ),
        lastXcodeUpgradeCheck: "16.0.0"
    )
)
